# Generated by Django 5.0.1 on 2024-02-29 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('section', models.TextField()),
                ('content', models.TextField()),
                ('correctAnswer', models.CharField(max_length=250)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
