# Generated by Django 5.0.1 on 2024-03-05 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfadmin.questionsection'),
        ),
    ]
